development:
  cloud_name: hlveaar2e
  api_key: '317864232882171'
  api_secret: ntwtCQnIaaedKv4KwxEfthwEupg
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hlveaar2e
  api_key: '317864232882171'
  api_secret: ntwtCQnIaaedKv4KwxEfthwEupg
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hlveaar2e
  api_key: '317864232882171'
  api_secret: ntwtCQnIaaedKv4KwxEfthwEupg
  enhance_image_tag: true
  static_image_support: false